// © 2026 WiamLabs. All rights reserved.
// lib/countries.js
// Every country in the world — the marketing site's registration
// form is not Ghana-only or Africa-only. Flags computed from ISO
// codes, not hand-typed. Free, no API, no dependency on anything
// external. Mirrors mobile/constants/countries.js exactly.

export const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', phoneCode: '+93' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', phoneCode: '+355' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', phoneCode: '+213' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', phoneCode: '+376' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', phoneCode: '+244' },
  { name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬', phoneCode: '+1268' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', phoneCode: '+54' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', phoneCode: '+374' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', phoneCode: '+61' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', phoneCode: '+43' },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', phoneCode: '+994' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', phoneCode: '+1242' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', phoneCode: '+973' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', phoneCode: '+880' },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧', phoneCode: '+1246' },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', phoneCode: '+375' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', phoneCode: '+32' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', phoneCode: '+501' },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', phoneCode: '+229' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', phoneCode: '+975' },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴', phoneCode: '+591' },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', phoneCode: '+387' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', phoneCode: '+267' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', phoneCode: '+55' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳', phoneCode: '+673' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', phoneCode: '+359' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', phoneCode: '+226' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', phoneCode: '+257' },
  { name: 'Cabo Verde', code: 'CV', flag: '🇨🇻', phoneCode: '+238' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', phoneCode: '+855' },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', phoneCode: '+237' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', phoneCode: '+1' },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫', phoneCode: '+236' },
  { name: 'Chad', code: 'TD', flag: '🇹🇩', phoneCode: '+235' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', phoneCode: '+56' },
  { name: 'China', code: 'CN', flag: '🇨🇳', phoneCode: '+86' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', phoneCode: '+57' },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲', phoneCode: '+269' },
  { name: 'Congo (Brazzaville)', code: 'CG', flag: '🇨🇬', phoneCode: '+242' },
  { name: 'Congo (DRC)', code: 'CD', flag: '🇨🇩', phoneCode: '+243' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', phoneCode: '+506' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', phoneCode: '+385' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', phoneCode: '+53' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', phoneCode: '+357' },
  { name: 'Czechia', code: 'CZ', flag: '🇨🇿', phoneCode: '+420' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', phoneCode: '+45' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', phoneCode: '+253' },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲', phoneCode: '+1767' },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', phoneCode: '+1809' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', phoneCode: '+593' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', phoneCode: '+20' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', phoneCode: '+503' },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', phoneCode: '+240' },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷', phoneCode: '+291' },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪', phoneCode: '+372' },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿', phoneCode: '+268' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', phoneCode: '+251' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', phoneCode: '+679' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', phoneCode: '+358' },
  { name: 'France', code: 'FR', flag: '🇫🇷', phoneCode: '+33' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', phoneCode: '+241' },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲', phoneCode: '+220' },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', phoneCode: '+995' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', phoneCode: '+49' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', phoneCode: '+233' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', phoneCode: '+30' },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩', phoneCode: '+1473' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', phoneCode: '+502' },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳', phoneCode: '+224' },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', phoneCode: '+245' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', phoneCode: '+592' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', phoneCode: '+509' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', phoneCode: '+504' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', phoneCode: '+36' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', phoneCode: '+354' },
  { name: 'India', code: 'IN', flag: '🇮🇳', phoneCode: '+91' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', phoneCode: '+62' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', phoneCode: '+98' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', phoneCode: '+964' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', phoneCode: '+353' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', phoneCode: '+972' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', phoneCode: '+39' },
  { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', phoneCode: '+225' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', phoneCode: '+1876' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', phoneCode: '+81' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', phoneCode: '+962' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', phoneCode: '+7' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', phoneCode: '+254' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', phoneCode: '+686' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', phoneCode: '+965' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', phoneCode: '+996' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', phoneCode: '+856' },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', phoneCode: '+371' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', phoneCode: '+961' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', phoneCode: '+266' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', phoneCode: '+231' },
  { name: 'Libya', code: 'LY', flag: '🇱🇾', phoneCode: '+218' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', phoneCode: '+423' },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', phoneCode: '+370' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', phoneCode: '+352' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', phoneCode: '+261' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', phoneCode: '+265' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', phoneCode: '+60' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', phoneCode: '+960' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', phoneCode: '+223' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', phoneCode: '+356' },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭', phoneCode: '+692' },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷', phoneCode: '+222' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', phoneCode: '+230' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', phoneCode: '+52' },
  { name: 'Micronesia', code: 'FM', flag: '🇫🇲', phoneCode: '+691' },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩', phoneCode: '+373' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', phoneCode: '+377' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', phoneCode: '+976' },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', phoneCode: '+382' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', phoneCode: '+212' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', phoneCode: '+258' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', phoneCode: '+95' },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦', phoneCode: '+264' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', phoneCode: '+674' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', phoneCode: '+977' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', phoneCode: '+31' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', phoneCode: '+64' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', phoneCode: '+505' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪', phoneCode: '+227' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', phoneCode: '+234' },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵', phoneCode: '+850' },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰', phoneCode: '+389' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', phoneCode: '+47' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', phoneCode: '+968' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', phoneCode: '+92' },
  { name: 'Palau', code: 'PW', flag: '🇵🇼', phoneCode: '+680' },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', phoneCode: '+970' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', phoneCode: '+507' },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', phoneCode: '+675' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', phoneCode: '+595' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', phoneCode: '+51' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', phoneCode: '+63' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', phoneCode: '+48' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', phoneCode: '+351' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', phoneCode: '+974' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', phoneCode: '+40' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', phoneCode: '+7' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', phoneCode: '+250' },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', phoneCode: '+1869' },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨', phoneCode: '+1758' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨', phoneCode: '+1784' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', phoneCode: '+685' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲', phoneCode: '+378' },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', phoneCode: '+239' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', phoneCode: '+966' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', phoneCode: '+221' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', phoneCode: '+381' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', phoneCode: '+248' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', phoneCode: '+232' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', phoneCode: '+65' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', phoneCode: '+421' },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', phoneCode: '+386' },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧', phoneCode: '+677' },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴', phoneCode: '+252' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', phoneCode: '+27' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', phoneCode: '+82' },
  { name: 'South Sudan', code: 'SS', flag: '🇸🇸', phoneCode: '+211' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', phoneCode: '+34' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', phoneCode: '+94' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩', phoneCode: '+249' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', phoneCode: '+597' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', phoneCode: '+46' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', phoneCode: '+41' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', phoneCode: '+963' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', phoneCode: '+886' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', phoneCode: '+992' },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', phoneCode: '+255' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', phoneCode: '+66' },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱', phoneCode: '+670' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', phoneCode: '+228' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', phoneCode: '+676' },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', phoneCode: '+1868' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', phoneCode: '+216' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', phoneCode: '+90' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', phoneCode: '+993' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', phoneCode: '+688' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', phoneCode: '+256' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', phoneCode: '+380' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', phoneCode: '+971' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', phoneCode: '+44' },
  { name: 'United States', code: 'US', flag: '🇺🇸', phoneCode: '+1' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', phoneCode: '+598' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', phoneCode: '+998' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', phoneCode: '+678' },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦', phoneCode: '+379' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', phoneCode: '+58' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', phoneCode: '+84' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', phoneCode: '+967' },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲', phoneCode: '+260' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', phoneCode: '+263' },
];

export const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.code === 'GH');
